services:
  - type: web
    name: denominator-is-worthless
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        value: mongodb://mongo:27017/denominator
    disk:
      name: mongo-data
      mountPath: /data/db
      sizeGB: 1

  - type: pserv
    name: denominator-mongo
    runtime: docker
    dockerfilePath: ./mongo.Dockerfile
    disk:
      name: mongo-data
      mountPath: /data/db
      sizeGB: 1
    envVars:
      - key: MONGO_INITDB_DATABASE
        value: denominator
